---
language: node_js
node_js: "12"
cache: yarn

dist: bionic

addons:
  chrome: stable

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master

script:
  - yarn ci

after_script:
  - yarn ci:report:codacy
  - yarn ci:report:coveralls
